Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,5 +14,9 @@ jobs:
         run: |
           FLAG_STATUS=$(curl -s -H "Authorization: api-e97b27cb-a2bb-4928-a864-d01374b489d3" \
                           "https://app.launchdarkly.com/api/v2/flags/sdk-79037d1d-f7c5-4380-ba2a-9f0611717500/Status_Flag")
+          if [ "$FLAG_STATUS" == "null" ]; then
+            echo "Error: Feature flag status is null. Please check your API key, project key, and flag key."
+            exit 1
+          fi
           FLAG_ENABLED=$(echo $FLAG_STATUS | jq -r '.enabled')
           echo "Feature Flag Status: $FLAG_ENABLED"
